name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: echo "No dependencies for now, just checking pipeline"

      - name: Run check
        run: echo "Pipeline running successfully!"
